### PR TITLE
Updated citation

### PR DESCRIPTION
**Pull request by nilseling**
This is to update the citation to `steinbock`.

### CODE REVIEW

**Comment by jwindhager** [comment]
LGTM - should we still mention the preprint, as long as the publication is not available open access (or that we can share the PDF upon request if needed)?

**Review by jwindhager — COMMENTED** [review]
LGTM - should we still mention the preprint, as long as the publication is not available open access (or that we can share the PDF upon request if needed)?

**Comment by nilseling** [comment]
That's a good idea. I have added a note that we can share the PDF

**Review by jwindhager — APPROVED** [review]

**Comment by Milad4849** [comment]
lgtm, mergin this

**Comment by Milad4849** [comment]
The push to main failed, running pytest inside the container returns [an error](https://github.com/BodenmillerGroup/steinbock/actions/runs/6945091416/job/18893670726#step:4:92), it seems that there is currently an incompatibility between napari and pydantic (https://github.com/napari/napari/issues/6350). The only fix seems to be to pin pydantic to a version < 2. @jwindhager would you advise it? can it be done by including and version pinning pydantic in  [requirements_test.txt](https://github.com/BodenmillerGroup/steinbock/blob/main/requirements_test.txt)?

**Pull request merged**
