### PR TITLE
Improve DeepCell/Mesmer documentation

### PR DESCRIPTION
**Pull request by jwindhager**
Directly merging this into main, to update the live online documentation for the revisions

### CODE REVIEW

**Comment by nilseling** [comment]
For the `--preprocess`/`--postprocess` options I would copy/paste the example you give into a text file, save it at `preprocess.yaml` and use it. Would this work or is there more formatting that I would need to do?

**Comment by jwindhager** [comment]
You mean for the manuscript? That should work (the example includes default values, so nothing should change).

**Comment by nilseling** [comment]
I mean for the way the docs are formatted

**Comment by jwindhager** [comment]
Sorry, me being silly: was this just a question, or do you want me to change something in the docs?

**Comment by nilseling** [comment]
No no, this was just a question. Or maybe to remind you that people might just copy/paste the 

```
        threshold: true
        percentile: 99.9
        normalize: true
        kernel_size: 128
```

part into a file.

**Comment by jwindhager** [comment]
Great, thanks - copying this to a file is the intended way. Could you approve the PR, maybe? Cheers :-)

**Review by nilseling — APPROVED** [review]
Very good

**Pull request merged**
